title: My Life Transitioning to Coding
author: Levi Milli
email: levi.millikin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is  where I'll be writing  about my  life  as a new coder, having a gamer background and seeing the 
  diffictulties and opportunities that come from it. On this journey I hope  to explore  my  own limitations 
  and push  them far beyond what was previously thought capable, while helping everyone who reads this find 
  thier own limitations and destroy them.
theme: minima
# social links
twitter_username: tiltlordape # DO NOT include the @ character, or else the build will fail!
github_username:  tiltlordflexnuts # DO NOT include the @ character, or else the build will fail!
instagram_username: vegasvi

show_excerpts: true # set to false to remove excerpts on the homepage
